//Mikhail Savvateev
//CSE 154 Section CB
//TA: Sam Tisdale
// CSE 154 ASCIIMation
// This is my custom animation to be used by the overall program.
// It was automatically generated by the StringMaker tool.
// (Paste this code as the contents of your myanimation.js file.)

var CUSTOM =
"  o\n" + 
"__|__\n" + 
"  |\n" + 
"  /\\\n" + 
" /  \\O\n" + 
"=====\n" + 
"  o\n" + 
"__|__\n" + 
"  |\n" + 
"  /\\\n" + 
" / / O\n" + 
"=====\n" + 
"  o\n" + 
"__|__\n" + 
"  |\n" + 
"  /\\\n" + 
" /  \\0\n" + 
"=====\n" + 
"  o\n" + 
"__|__\n" + 
"  |\n" + 
"  /\\__ \n" + 
" /    O\n" + 
"=====\n" + 
"  o\n" + 
"__|__\n" + 
"  |    O\n" + 
"  /\\/  \n" + 
" /  \n" + 
"=====\n" + 
"  o\n" + 
"__|__    O\n" + 
"  |    \n" + 
"  /\\\\  \n" + 
" /  \n" + 
"=====\n" + 
"  o          O\n" + 
"__|__    \n" + 
"  |    \n" + 
"  /\\  \n" + 
" /  \n" + 
"=====\n" + 
"  o          0\n" + 
"__|__             \n" + 
"  |    \n" + 
"  /_\\  \n" + 
" /  \n" + 
"=====\n" + 
"  o          (())\n" + 
"__|__             \n" + 
"  |    \n" + 
"  /\\  \n" + 
" / / \n" + 
"=====\n" + 
"  o         ((()))\n" + 
"__|__             \n" + 
"  |    \n" + 
"  /\\  \n" + 
" /  |\n" + 
"=====\n" + 
"  o         ((  ))\n" + 
"__|__         /   \n" + 
"  |          /  \n" + 
"  /\\  \n" + 
" /  \\\n" + 
"=====\n" + 
"  o         (    )\n" + 
"__|__            \n" + 
"  |          /  \n" + 
"  /\\        / \n" + 
" /  \\    ()/\n" + 
"=====\n" + 
"  o        \n" + 
"__|__            \n" + 
"  |          \n" + 
"  /\\         \n" + 
" /  \\    0\n" + 
"=====\n" + 
"  o        \n" + 
"__|__            \n" + 
"  |          \n" + 
"  /\\         \n" + 
" /  \\    O\n" + 
"=====\n" + 
"  o        \n" + 
"__|__            \n" + 
"  |          \n" + 
"  /\\         \n" + 
" /  \\   O\n" + 
"=====\n" + 
"  o        \n" + 
"__|__            \n" + 
"  |          \n" + 
"  /\\         \n" + 
" /  \\  O\n" + 
"=====\n" + 
"  o        \n" + 
"__|__            \n" + 
"  |          \n" + 
"  /\\         \n" + 
" /  \\O\n" + 
"=====\n" + 
"  o        \n" + 
"__|__            \n" + 
"  |          \n" + 
"  /\\         \n" + 
" /  \\O\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;
